### ISSUE TITLE
Segmentation Fault in Darwin (macOS High Sierra 10.13.1)

### ISSUE THREAD

**Issue by aj-foster** [mmore500/git-commit-atom#6]
Hello there!

Somewhere between the 0.5.0 release and the 0.6.0 release, something changed in the pre-built binaries that causes a segmentation fault in macOS. 0.5.0's release works great, but 0.6.0 and 0.6.1 have the same issue. Since it doesn't appear there were any relevant code changes between those releases, I suspect that a supporting package might have changed.

The following could be a red herring, but here's the output of `dtruss` when the fault occurs:

<details>
<summary>Click to expand</summary>

```
$ ❯ sudo dtruss -a ~/Downloads/git-commit-atom\ 2 .git/COMMIT_EDITMSG 
dtrace: system integrity protection is on, some features will not be available

	PID/THRD  RELATIVE  ELAPSD    CPU SYSCALL(args) 		 = return
dtrace: error on enabled probe ID 2190 (ID 557: syscall::sysctl:return): invalid kernel access in action #11 at DIF offset 40
12825/0x22050f:      1370     909    904 mmap(0xC000000000, 0x8820002000, 0x0, 0x1002, 0xFFFFFFFFFFFFFFFF, 0x0)		 = 0xC000000000 0
12825/0x22050f:      1391       5      1 mmap(0x0, 0x40000, 0x3, 0x1002, 0xFFFFFFFFFFFFFFFF, 0x0)		 = 0x319000 0
12825/0x22050f:      1419       8      5 mmap(0xC820000000, 0x100000, 0x3, 0x1012, 0xFFFFFFFFFFFFFFFF, 0x0)		 = 0xC820000000 0
12825/0x22050f:      1422       4      2 mmap(0xC81FFF8000, 0x8000, 0x3, 0x1012, 0xFFFFFFFFFFFFFFFF, 0x0)		 = 0xC81FFF8000 0
12825/0x22050f:      1424       4      1 mmap(0xC000000000, 0x1000, 0x3, 0x1012, 0xFFFFFFFFFFFFFFFF, 0x0)		 = 0xC000000000 0
12825/0x22050f:      1427       3      1 mmap(0x0, 0x10000, 0x3, 0x1002, 0xFFFFFFFFFFFFFFFF, 0x0)		 = 0x359000 0
12825/0x22050f:      1439       4      0 gettimeofday(0x7FFEEFBFF640, 0x0, 0x2C66E0)		 = 0 0
12825/0x22050f:      1444       4      1 gettimeofday(0x7FFEEFBFF698, 0x0, 0x1)		 = -1 Err#14

CALL                                        COUNT
sysctl                                          1
gettimeofday                                    2
mmap                                            6
```

</details>

**Comment by mmore500** [comment]
I pulled out an old mac and was able to duplicate the segfault. I recompiled the golang script on the mac and was able to run it without a segfault. I just updated the binaries available on the release pages with working copies. Not sure what the issue was (one of the linux binaries I tried worked just fine on my Elementary install) but hopefully this fixes it! Let me know if it works for you.

**Comment by aj-foster** [comment]
The updated binary works for me! Thanks for looking into it.
